/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uthh.edd.unidad1.tda.TDAVisual;

/**
 *
 * @author Humberto Flores Castillo
 */
public class FrmCalcularPromedio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCalcularPromedio.class.getName());
    
    //Crea y configura los elementos visuales
    public FrmCalcularPromedio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblCalif1 = new javax.swing.JLabel();
        lblCalif2 = new javax.swing.JLabel();
        lblCalif3 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtCalif1 = new javax.swing.JTextField();
        txtCalif2 = new javax.swing.JTextField();
        txtCalif3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblAlumno = new javax.swing.JLabel();
        lblPromedio = new javax.swing.JLabel();
        lblCalifMayor = new javax.swing.JLabel();
        lblAprobado = new javax.swing.JLabel();
        lblCalifMenor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombre.setText("Nombre:");
        lblNombre.setName("lblNombre"); // NOI18N

        lblCalif1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCalif1.setText("Calificacion 1er Parcial:");
        lblCalif1.setName("lblCalif1"); // NOI18N

        lblCalif2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCalif2.setText("Calificacion 2do Parcial:");
        lblCalif2.setName("lblCalif2"); // NOI18N

        lblCalif3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCalif3.setText("Calificacion 3er Parcial:");
        lblCalif3.setName("lblCalif3"); // NOI18N

        btnCalcular.setBackground(new java.awt.Color(249, 200, 200));
        btnCalcular.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCalcular.setText("CALCULAR");
        btnCalcular.setName("Calcular"); // NOI18N
        btnCalcular.addActionListener(this::btnCalcularActionPerformed);

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombre.setName("txtNombre"); // NOI18N

        txtCalif1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCalif1.setName("txtCalif1"); // NOI18N

        txtCalif2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCalif2.setName("txtCalif2"); // NOI18N
        txtCalif2.addActionListener(this::txtCalif2ActionPerformed);

        txtCalif3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCalif3.setName("txtCalif3"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(214, 234, 234));

        lblAlumno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAlumno.setText("[.......................]");
        lblAlumno.setName("lblPromedio"); // NOI18N

        lblPromedio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPromedio.setText("[.......................]");
        lblPromedio.setName("lblPromedio"); // NOI18N

        lblCalifMayor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCalifMayor.setText("[.......................]");
        lblCalifMayor.setName("lblCalifMayor"); // NOI18N

        lblAprobado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAprobado.setText("[.......................]");
        lblAprobado.setName("lblAprobatorio"); // NOI18N

        lblCalifMenor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCalifMenor.setText("[.......................]");
        lblCalifMenor.setName("lblCalifMenor"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblAlumno)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCalifMenor)
                            .addComponent(lblCalifMayor))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPromedio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                        .addComponent(lblAprobado)
                        .addGap(138, 138, 138))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblAlumno)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblAprobado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblPromedio)
                        .addGap(18, 18, 18)
                        .addComponent(lblCalifMayor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCalifMenor)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(107, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCalif3)
                            .addComponent(lblCalif2)
                            .addComponent(lblCalif1)
                            .addComponent(lblNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCalif2, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(txtNombre)
                            .addComponent(txtCalif1)
                            .addComponent(txtCalif3))
                        .addContainerGap(200, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCalif1)
                    .addComponent(txtCalif1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCalif2)
                    .addComponent(txtCalif2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCalif3)
                    .addComponent(txtCalif3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Metodo ligado al evento del boton.
    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        try {
            String nombre = txtNombre.getText();

            double calif1 = Double.parseDouble(txtCalif1.getText());
            double calif2 = Double.parseDouble(txtCalif2.getText());
            double calif3 = Double.parseDouble(txtCalif3.getText());

            // Crea el objeto del TDA, envia los datos capturados del entorno visual
            CalcularPromedio alumno = new CalcularPromedio(
                nombre,
                calif1,
                calif2,
                calif3
            );

            //Promedio utilizando con método recursivo
            double promedio = alumno.calcularPromedioRecursivo();
        
            //Muestra el nombre del alumno
            lblAlumno.setText("Nombre: " + String.format(nombre));
            
            //Muestra el promedio
            lblPromedio.setText("Promedio: " + String.format("%.2f", promedio));

            // Mostrar calificación mayor
            lblCalifMayor.setText("Calificación mayor: " + alumno.calcularCalifMayor());

            // Mostrar calificación menor
            lblCalifMenor.setText("Calificación menor: " + alumno.calcularCalifMenor()
            );

            // Mostrar estado del alumno
            if (alumno.estaAprobado()) {
                lblAprobado.setText("Estado: Aprobado");
            } else {
                lblAprobado.setText("Estado: Reprobado");
            }

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,"Ingresa valores numéricos válidos en las calificaciones.",
                "Error",javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtCalif2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalif2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalif2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmCalcularPromedio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAlumno;
    private javax.swing.JLabel lblAprobado;
    private javax.swing.JLabel lblCalif1;
    private javax.swing.JLabel lblCalif2;
    private javax.swing.JLabel lblCalif3;
    private javax.swing.JLabel lblCalifMayor;
    private javax.swing.JLabel lblCalifMenor;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPromedio;
    private javax.swing.JTextField txtCalif1;
    private javax.swing.JTextField txtCalif2;
    private javax.swing.JTextField txtCalif3;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
